os:
  - 'linux'
  - 'osx'
language: python
python:
  - '2.7'
  - '3.4'
install:
  - pip install -r ./requirements/ci.txt
script:
  - py.test --doctest-modules --verbose ./il2fb/config/difficulty ./tests --cov ./il2fb/config/difficulty ./tests
after_success:
  - codecov
  - ocular --data-file ".coverage" --config-file ".coveragerc"
notifications:
  email: false
  slack:
    secure: FSe4nHo5MNmHNnKCx0DXZb0YI6LgPcQ1dg2maN3PatEODaboXiwKTfFmghdVPxERvT7voeCWtuvlirXzv9QuiGkopVcCdiV9vs0/VQQeLJEBT0wSc6unILe/2jSeuoLcYMa6PBcCmLh1kaILYnVxwjRIet/DHQPStXfLEd8/WUo=
